'use strict';
module.exports = {
  protocol: {
    id: { type: 'number', description: 'The row id', example: 1 },
    name: { type: 'string', description: 'The protocol name', example: 'swap.defi' },
    category: { type: 'string', description: 'The category of protocol', example: 'dexes' },
    metadata_name: { type: 'string', description: 'The metadata name of protocol', example: 'Defibox swap' },
    tvl_eos: { type: 'number', description: 'The tvl of eos valuation', example: 7201852.2869 },
    tvl_usd: { type: 'number', description: 'The tvl of usd valuation', example: 7452485.8847 },
    tvl_eos_change_8h: { type: 'number', description: 'tvl 8h change(eos valuation)', example: -38774.5351 },
    tvl_usd_change_8h: { type: 'number', description: 'tvl 8h change(usd valuation)', example: 46644.4095 },
    tvl_eos_change_day: { type: 'number', description: 'tvl 24h change(eos valuation)', example: -128194.464 },
    tvl_usd_change_day: { type: 'number', description: 'tvl 24h change(usd valuation)', example: 159133.8179 },
    tvl_eos_change_week: { type: 'number', description: 'tvl week change(eos valuation)', example: 102771.0034 },
    tvl_usd_change_week: { type: 'number', description: 'tvl week change(usd valuation)', example: -1908.3507 },
    agg_rewards: { type: 'number', description: 'The aggregate rewards', example: 16112.8371 },
    agg_rewards_change: { type: 'number', description: 'The aggregate rewards 24h change', example: 827.6165 },
    contracts: { type: 'string', description: 'The additional supporting EOS contracts', example: [ 'swap.defi' ] },
    evm: { type: 'string', description: 'The additional supporting EVM contracts', example: [] },
    metadata: { type: 'string', description: 'The protocol metadata', example: { name: 'Danchor', url: 'https://defibox.io/usn' } },
    balance: { type: 'number', description: 'The balance rewards', example: 23041.9849 },
    claimed: { type: 'number', description: 'The claimed rewards', example: 0 },
    rewards: { type: 'number', description: 'The reward', example: 3.1201000000 },
    status: { type: 'string', description: 'The protocol status: pending,active,denied', example: 'active' },
    period: { type: 'number', description: 'The period time', example: 1658190600 },
    rewards_period: { type: 'number', description: 'The rewards period time', example: 1658190600 },
    is_delete: { type: 'number', description: 'The delete status (1: deleted 0: not deleted)', example: 0 },
    create_at: { type: 'number', description: 'The protocol create timestamp', example: 1655472145 },
  },
  protocol_stat: {
    id: { type: 'number', description: 'The row id', example: 1 },
    tvl_eos: { type: 'number', description: 'The tvl of eos valuation', example: 7201852.2869 },
    tvl_usd: { type: 'number', description: 'The tvl of usd valuation', example: 7452485.8847 },
    tvl_eos_change_8h: { type: 'number', description: 'tvl 8h change(eos valuation)', example: -38774.5351 },
    tvl_usd_change_8h: { type: 'number', description: 'tvl 8h change(usd valuation)', example: 46644.4095 },
    tvl_eos_change_day: { type: 'number', description: 'tvl 24h change(eos valuation)', example: -128194.464 },
    tvl_usd_change_day: { type: 'number', description: 'tvl 24h change(usd valuation)', example: 159133.8179 },
    tvl_eos_change_week: { type: 'number', description: 'tvl week change(eos valuation)', example: 102771.0034 },
    tvl_usd_change_week: { type: 'number', description: 'tvl week change(usd valuation)', example: -1908.3507 },
    agg_rewards: { type: 'number', description: 'The aggregate rewards', example: 16112.8371 },
    agg_rewards_change: { type: 'number', description: 'The aggregate rewards 24h change', example: 827.6165 },
    agg_protocol_count: { type: 'number', description: 'The aggregate protocol count', example: 6 },
    claimed: { type: 'number', description: 'The claimed rewards', example: 0 },
    period: { type: 'number', description: 'The period time', example: 1658190600 },
    rewards_period: { type: 'number', description: 'The rewards period time', example: 1658190600 },
  },
  protocolt_category_stat: {
    id: { type: 'number', description: 'The row id', example: 1 },
    category: { type: 'string', description: 'The category of protocol', example: 'dexes' },
    tvl_eos: { type: 'number', description: 'The tvl of eos valuation', example: 7201852.2869 },
    tvl_usd: { type: 'number', description: 'The tvl of usd valuation', example: 7452485.8847 },
    tvl_eos_change_8h: { type: 'number', description: 'tvl 8h change(eos valuation)', example: -38774.5351 },
    tvl_usd_change_8h: { type: 'number', description: 'tvl 8h change(usd valuation)', example: 46644.4095 },
    tvl_eos_change_day: { type: 'number', description: 'tvl 24h change(eos valuation)', example: -128194.464 },
    tvl_usd_change_day: { type: 'number', description: 'tvl 24h change(usd valuation)', example: 159133.8179 },
    tvl_eos_change_week: { type: 'number', description: 'tvl week change(eos valuation)', example: 102771.0034 },
    tvl_usd_change_week: { type: 'number', description: 'tvl week change(usd valuation)', example: -1908.3507 },
    agg_rewards: { type: 'number', description: 'The aggregate rewards', example: 16112.8371 },
    agg_rewards_change: { type: 'number', description: 'The aggregate rewards 24h change', example: 827.6165 },
    agg_protocol_count: { type: 'number', description: 'The aggregate protocol count', example: 6 },
    claimed: { type: 'number', description: 'The claimed rewards', example: 0 },
    period: { type: 'number', description: 'The period time', example: 1658190600 },
    rewards_period: { type: 'number', description: 'The rewards period time', example: 1658190600 },
  },
  line: {
    line_id: { type: 'number', description: 'The timestamp', example: 1656288000 },
    name: { type: 'string', description: 'The protocol name', example: 'swap.defi' },
    tvl_eos: { type: 'number', description: 'The tvl of eos valuation', example: 7201852.2869 },
    tvl_usd: { type: 'number', description: 'The tvl of usd valuation', example: 7452485.8847 },
    tvl_eos_change: { type: 'number', description: 'tvl change for different line_type(eos valuation)', example: -119427.7451 },
    tvl_usd_change: { type: 'number', description: 'tvl change for different line_type(usd valuation)', example: 152336.7599 },
    agg_rewards: { type: 'number', description: 'The aggregate rewards', example: 16112.8371 },
    agg_rewards_change: { type: 'number', description: 'The aggregate rewards 24h change', example: 827.6165 },
  },
  line_stat: {
    line_id: { type: 'number', description: 'The timestamp', example: 1656288000 },
    tvl_eos: { type: 'number', description: 'The tvl of eos valuation', example: 7201852.2869 },
    tvl_usd: { type: 'number', description: 'The tvl of usd valuation', example: 7452485.8847 },
    tvl_eos_change: { type: 'number', description: 'tvl change for different line_type(eos valuation)', example: -119427.7451 },
    tvl_usd_change: { type: 'number', description: 'tvl change for different line_type(usd valuation)', example: 152336.7599 },
    agg_rewards: { type: 'number', description: 'The aggregate rewards', example: 16112.8371 },
    agg_rewards_change: { type: 'number', description: 'The aggregate rewards 24h change', example: 827.6165 },
    agg_protocol_count: { type: 'number', description: 'The aggregate protocol count', example: 6 },
  },
  line_category_stat: {
    line_id: { type: 'number', description: 'The timestamp', example: 1656288000 },
    category: { type: 'string', description: 'The category of protocol', example: 'dexes' },
    tvl_eos: { type: 'number', description: 'The tvl of eos valuation', example: 7201852.2869 },
    tvl_usd: { type: 'number', description: 'The tvl of usd valuation', example: 7452485.8847 },
    tvl_eos_change: { type: 'number', description: 'tvl change for different line_type(eos valuation)', example: -119427.7451 },
    tvl_usd_change: { type: 'number', description: 'tvl change for different line_type(usd valuation)', example: 152336.7599 },
    agg_rewards: { type: 'number', description: 'The aggregate rewards', example: 16112.8371 },
    agg_rewards_change: { type: 'number', description: 'The aggregate rewards 24h change', example: 827.6165 },
    agg_protocol_count: { type: 'number', description: 'The aggregate protocol count', example: 6 },
  },
  chain_node: {
    chain: { type: 'string', description: 'The chain eg: wax eos', example: 'eos' },
    chain_id: { type: 'string', description: 'The chain id', example: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906' },
    url: { type: 'string', description: 'The node url', example: 'https://eos.defibox.xyz' },
    area: { type: 'string', description: 'area', example: 'Hongkong' },
    is_default: { type: 'number', description: 'The is default node', example: 0 },
  },
  ipfs_result: {
    ipfs_hash: { type: 'string', description: 'The ipfs hash', example: 'QmdBmRHDNomHSn5uE1e3gekgo5n7y61HKrfgYMCvfWrYPi' },
    pin_size: { type: 'string', description: 'The pin size', example: 8740 },
    timestamp: { type: 'string', description: 'The timestamp', example: '2022-07-26T06:55:45.942Z' },
    is_duplicate: { type: 'boolean', description: 'The duplicate upload status', example: true },
  },
  report: {
    id: { type: 'number', description: 'The report id', example: 1 },
    title: { type: 'string', description: 'Report title', example: 'November 2022 Yield+ Report' },
    url: { type: 'string', description: 'Report detail link', example: '"https://eosnetwork.com/blog/november-2022-yield-report/' },
    image: { type: 'string', description: 'Report image', example: 'https://eosnetwork.com/wp-content/uploads/2022/12/Yield_Report_November-1024x512.png' },
    remark: { type: 'string', description: 'The remark', example: '' },
  },
};
